### ISSUE TITLE
优化一下

### ISSUE THREAD

**Issue by CasualMing** [hepengwei/visualization-collection#116]
本来想将项目下载到本地进行优化一下之后再提一个pr
结果在项目运行的时候，不是这错就是那错，整的措手不及
个人建议博主使用 webpack-bundle-analyzer 插件分析一下打包的情况，
然后进行一下分包，然后看到项目中有使用到很多第三方库，这些库是否有进行按需加载

**Comment by xia-2** [comment]
我刚clone下来看了下，基本上是些warning，不影响运行
```
git clone xxx
yarn # 他用的是yarn包管理，不要用pnpm或者npm，如果你看到error可能是包管理工具的问题
yarn run dev
```
可以运行，运行后显示很多warn，渲染出来的浏览器界面里，你在右上角可以看到一个叉叉，关掉就行，界面正常运行。

**Comment by hepengwei** [comment]
> 我刚clone下来看了下，基本上是些warning，不影响运行
> 
> ```
> git clone xxx
> yarn # 他用的是yarn包管理，不要用pnpm或者npm，如果你看到error可能是包管理工具的问题
> yarn run dev
> ```
> 
> 可以运行，运行后显示很多warn，渲染出来的浏览器界面里，你在右上角可以看到一个叉叉，关掉就行，界面正常运行。

是的，这些后面有时间了都会去慢慢解决的，目前在逐步给所有页面添加中英文切换，今天回去还要开发个新功能，所以那些就有时间了去解决，也感谢你的支持，觉得不错的话，记得帮忙推荐哦

**Comment by lxge** [comment]
> > 我刚clone下来看了下，基本上是些warning，不影响运行
> > ```
> > git clone xxx
> > yarn # 他用的是yarn包管理，不要用pnpm或者npm，如果你看到error可能是包管理工具的问题
> > yarn run dev
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 可以运行，运行后显示很多warn，渲染出来的浏览器界面里，你在右上角可以看到一个叉叉，关掉就行，界面正常运行。
> 
> 是的，这些后面有时间了都会去慢慢解决的，目前在逐步给所有页面添加中英文切换，今天回去还要开发个新功能，所以那些就有时间了去解决，也感谢你的支持，觉得不错的话，记得帮忙推荐哦

大佬这都是用react去写的, 可以在vue中使用吗, 需要自己改改不同的语法吧

**Comment by hepengwei** [comment]
当然可以在vue中使用，sass样式和JS代码都是通用的，只是在vue中要适配vue的语法而已




你的幸福、我赞助
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hepengwei/visualization-collection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月29日(星期三) 上午9:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hepengwei/visualization-collection] 优化一下 (Issue #116)





   
我刚clone下来看了下，基本上是些warning，不影响运行
 git clone xxx yarn # 他用的是yarn包管理，不要用pnpm或者npm，如果你看到error可能是包管理工具的问题 yarn run dev  
可以运行，运行后显示很多warn，渲染出来的浏览器界面里，你在右上角可以看到一个叉叉，关掉就行，界面正常运行。
  
是的，这些后面有时间了都会去慢慢解决的，目前在逐步给所有页面添加中英文切换，今天回去还要开发个新功能，所以那些就有时间了去解决，也感谢你的支持，觉得不错的话，记得帮忙推荐哦
  
大佬这都是用react去写的, 可以在vue中使用吗, 需要自己改改不同的语法吧

**Comment by lxge** [comment]
> 当然可以在vue中使用，sass样式和JS代码都是通用的，只是在vue中要适配vue的语法而已 你的幸福、我赞助 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hepengwei/visualization-collection" ***@***.***&gt;; 发送时间:&nbsp;2023年3月29日(星期三) 上午9:48 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [hepengwei/visualization-collection] 优化一下 (Issue #116) 我刚clone下来看了下，基本上是些warning，不影响运行 git clone xxx yarn # 他用的是yarn包管理，不要用pnpm或者npm，如果你看到error可能是包管理工具的问题 yarn run dev 可以运行，运行后显示很多warn，渲染出来的浏览器界面里，你在右上角可以看到一个叉叉，关掉就行，界面正常运行。 是的，这些后面有时间了都会去慢慢解决的，目前在逐步给所有页面添加中英文切换，今天回去还要开发个新功能，所以那些就有时间了去解决，也感谢你的支持，觉得不错的话，记得帮忙推荐哦 大佬这都是用react去写的, 可以在vue中使用吗, 需要自己改改不同的语法吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好的, 有机会也要多尝试用react, 主要现在公司都用vue
