### ISSUE TITLE
标明出处？

### ISSUE THREAD

**Issue by susu-hu** [hepengwei/visualization-collection#153]
有些demo是搬运别人的吧，最好标明出处哦

**Comment by hepengwei** [comment]
这个没有必要，找的都是开源的，该项目也是开源的

**Comment by susu-hu** [comment]
视觉设计有4个，我在掘金发布过的文章

**Comment by li-jia-nan** [comment]
尊重原创🙏

**Comment by hepengwei** [comment]
> 视觉设计有4个，我在掘金发布过的文章

好的，你加下我微信15071206497，我们微信上聊

**Comment by susu-hu** [comment]
不了，你自己看着办吧 ，其实你可以在简介标明有搬运内容哈，毕竟你这里面的demo一眼眼熟的太多了，没有不让你搬运的意思哈

**Comment by hepengwei** [comment]
感谢理解，希望没有给你造成什么影响，本来还说跟你合作一下的
