### ISSUE TITLE
hepengwei.cn里，效果有了，为什么没有点击展开代码的东西。。？

### ISSUE THREAD

**Issue by jufjzq** [hepengwei/visualization-collection#159]

**Comment by hepengwei** [comment]
如果有了就可惜了，哈哈，开个玩笑。。。
我来回答一下这个问题：
因为该项目整体是使用React实现的，做过React项目的都知道，一个React页面或组件里（在这里就是每个案例）不光是只有该案例对应的文件或文件夹中的代码，它还引入了很多其他文件夹或文件中的方法，比如：可能会引入公共组件文件夹components中的某个组件，会引入公共hooks文件，还会引入公共的工具方法文件夹utils中的某个方法，还有的会使用全局的变量或sass变量，等等这些，那么如果将每个案例文件夹中对应的.tsx和.module.scss文件中的代码展示出来，大家是看不懂的，缺少很多其他文件中的代码，代码也是无法直接运行的，还是要具体结合整个项目源码看才行。
所以，综上所述，给每个案例添加点击展开代码是毫无意义的。

**Comment by jufjzq** [comment]
> 哈哈可惜，哈哈，哈哈可惜：开 我： 因为回答：因为因为：因为因为该该项目整体整体使用整体是是使用实现实现实现实现（（）不不光是有该案例案例案例或的的代码的，它夹中的中中中的夹的它它还引入引入了了很多其他其他其他文件夹或文件中的文件中中中的方法，比如文件中，比如文件文件，比如可能文件，可能可能，可能共钩文件，还还引入公公的工具方法方法文件文件文件文件文件文件中中的某某个某，还有的还有的个个个还有的会会使用全局全局的的的变量或或变量.module.scss文件文件代码，大家出来，大家懂懂，缺少不懂，缺少缺少其他文件中中中中，代码中中，代码代码也是直接直接直接运行，还是直接， 还是记，给每个案子添加点击展开代码是毫无意义的。

但是该怎么用呢，比如我看中了一个效果，希望用在我自己的vue项目里？这个网站不会只是展示一下而已吧。。。

**Comment by hepengwei** [comment]
你都已经在这个项目仓库，都已经看到源码了，咋的，还要别人喂你呗

**Comment by jufjzq** [comment]
> 你都已经在这个项目仓库，都已经看到源码了，咋的，还要别人喂你呗

6

**Comment by hqzh** [comment]
> 你都已经在这个项目仓库，都已经看到源码了，咋的，还要别人喂你呗
赞
