### ISSUE TITLE
canvas动效中的球体自由落体交互有个bug

### ISSUE THREAD

**Issue by ye001226** [hepengwei/visualization-collection#192]
在屏幕上方同一个地方连续点击

**Comment by hepengwei** [comment]
没问题哟，第二次点击是抓住球，每个球都是可以拖拽的

**Comment by ye001226** [comment]
> 没问题哟，第二次点击是抓住球，每个球都是可以拖拽的

抓住球的话不应该固定住吗，或者跟随鼠标移动

**Comment by ye001226** [comment]
https://github.com/hepengwei/visualization-collection/assets/139834430/af511995-5980-41e7-b46b-d69525f39752

**Comment by hepengwei** [comment]
> 77_1690510442.mp4

sphere-collision动画库的算法有点问题，有待优化，感谢你提出的问题
