### ISSUE TITLE
打包前运行正常，打包后会报这个错误，您知道怎么解决吗？感谢！

### ISSUE THREAD

**Issue by kkkhgk** [hepengwei/visualization-collection#197]
![image](https://github.com/hepengwei/visualization-collection/assets/108576904/b5df5a4a-81ed-4522-b4bc-00d58f7fac66)

**Comment by hepengwei** [comment]
> ![image](https://user-images.githubusercontent.com/108576904/266189268-b5df5a4a-81ed-4522-b4bc-00d58f7fac66.png)

你全局搜一下，这应该是你自己加的代码
