### ISSUE TITLE
http://hepengwei.cn/#/threejs/threejsAppPageFrame 这个页面下点击缩放左侧栏，右侧展示不全

### ISSUE THREAD

**Issue by haojiakui** [hepengwei/visualization-collection#205]
![image](https://github.com/hepengwei/visualization-collection/assets/43265075/e4910d7e-ed26-4c0f-8d52-737e5ac6b660)

**Comment by hepengwei** [comment]
不会啊，Chrome和Microsoft Edge浏览器我都试了，没有问题

**Comment by hepengwei** [comment]
是有这个问题，目前已修复，感谢你反馈的问题
